export const GET_FLIGHTS = "GET_FLIGHTS";
export const GET_FLIGHT_DETAILS = "GET_FLIGHT_DETAILS";
export const ADD_FLIGHT = "ADD_FLIGHT";
export const DELETE_FLIGHT = "DELETE_FLIGHT";
export const UPDATE_FLIGHT_TOURISTS = "UPDATE_FLIGHT_TOURISTS";
export const FLIGHT_ADD_TOURIST = "FLIGHT_ADD_TOURIST";
export const FLIGHT_REMOVE_TOURIST = "FLIGHT_REMOVE_TOURIST";
export const FLIGHTS_LOADING = "FLIGHTS_LOADING";

export const GET_TOURISTS = "GET_TOURISTS";
export const GET_TOURIST_DETAILS = "GET_TOURIST_DETAILS";
export const ADD_TOURIST = "ADD_TOURIST";
export const DELETE_TOURIST = "DELETE_TOURIST";
export const TOURIST_ADD_FLIGHT = "TOURIST_ADD_FLIGHT";
export const TOURIST_REMOVE_FLIGHT = "TOURIST_REMOVE_FLIGHT";
export const GET_TOURISTS_IN_FLIGHT = "GET_TOURISTS_IN_FLIGHT";
export const TOURISTS_LOADING = "TOURISTS_LOADING";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
